### PR TITLE
win_package - fix productId check before getting remote files

### LINKED ISSUE #479: ansible.windows.win_package continues to download .exe files originating from URL or UNC regardless of product_id
##### SUMMARY
The win_package module does not honor the product_id parameter for .exe files whose path type is URL or UNC until **after** the file has been downloaded. This results in the file being re-downloaded on every run regardless of the existence of the product_id in the registry.

I believe the issue is that the $Id variable used in [this statement](https://github.com/ansible-collections/ansible.windows/blob/1.13.0/plugins/modules/win_package.ps1#L1438) is never defined and should instead be replaced with either $getParams.Id or $productId

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_package

##### ANSIBLE VERSION

```paste below
  ansible [core 2.13.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/username/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection      Version
--------------- -------
ansible.windows 1.13.0
```

##### CONFIGURATION

```paste below
default
```

##### OS / ENVIRONMENT

target OS: various versions of Windows

##### STEPS TO REPRODUCE

Run a task using the win_package module to install an .exe file from URL or UNC path while providing the appropriate product_id parameter.

```yaml
- name: Install Visual C thingy
  ansible.windows.win_package:
    path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
    product_id: '{ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}'
    arguments:
    - /install
    - /passive
    - /norestart
```

##### EXPECTED RESULTS

After initial install, the vcredist_x64.exe file should no longer be downloaded since the specified product_id exists in the registry at HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}

##### ACTUAL RESULTS

The vcredist_x64.exe file continues to be downloaded on every run of the task, which can be observed on the remote host.  However, the file is not re-installed and the task results in changed=false since the product_id is honored **after** the download step.

Initial Run:
```paste below
TASK [starter-role : Install Visual C thingy
path=http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe, product_id={ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}, arguments=['/install', '/passive', '/norestart']] ***
task path: /tasks/install_dependencies.yml:24
Wednesday 15 March 2023  09:03:53 -0400 (0:00:00.070)       0:00:14.163 *******
Using module file /.cache/ansible-compat/b11e21/collections/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 55985 TO 127.0.0.1
EXEC (via pipeline wrapper)
changed: [starter-role-windows] => changed=true 
  elapsed: 6.470174699999999
  invocation:
    module_args:
      arguments:
      - /install
      - /passive
      - /norestart
      chdir: null
      client_cert: null
      client_cert_password: null
      creates_path: null
      creates_service: null
      creates_version: null
      expected_return_code:
      - 0
      - 3010
      follow_redirects: safe
      force_basic_auth: false
      headers: null
      http_agent: ansible-httpget
      log_path: null
      maximum_redirection: 50
      password: null
      path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
      product_id: '{ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}'
      provider: auto
      proxy_password: null
      proxy_url: null
      proxy_use_default_credential: false
      proxy_username: null
      state: present
      url_method: null
      url_password: null
      url_timeout: 30
      url_username: null
      use_default_credential: false
      use_proxy: true
      username: null
      validate_certs: true
      wait_for_children: false
  msg: OK
  rc: 0
  reboot_required: false
  status_code: 20
```
Subsequent run:
```paste below
TASK [starter-role : Install Visual C thingy
path=http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe, product_id={ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}, arguments=['/install', '/passive', '/norestart']] ***
task path: /tasks/install_dependencies.yml:24
Wednesday 15 March 2023  09:07:17 -0400 (0:00:00.049)       0:00:10.746 *******
Using module file /.cache/ansible-compat/b11e21/collections/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 55985 TO 127.0.0.1
EXEC (via pipeline wrapper)
ok: [starter-role-windows] => changed=false 
  elapsed: 6.4227305999999995
  invocation:
    module_args:
      arguments:
      - /install
      - /passive
      - /norestart
      chdir: null
      client_cert: null
      client_cert_password: null
      creates_path: null
      creates_service: null
      creates_version: null
      expected_return_code:
      - 0
      - 3010
      follow_redirects: safe
      force_basic_auth: false
      headers: null
      http_agent: ansible-httpget
      log_path: null
      maximum_redirection: 50
      password: null
      path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
      product_id: '{ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}'
      provider: auto
      proxy_password: null
      proxy_url: null
      proxy_use_default_credential: false
      proxy_username: null
      state: present
      url_method: null
      url_password: null
      url_timeout: 30
      url_username: null
      use_default_credential: false
      use_proxy: true
      username: null
      validate_certs: true
      wait_for_children: false
  msg: OK
  rc: 0
  reboot_required: false
  status_code: 200
```

### PR DESCRIPTION
**Pull request by AzadShM**
win_package should not download/copy $path before checking the installation status if product_id is set

##### SUMMARY
Based on the win_package documentation:
"When state=present, product_id is not set and the path is a URL, this file will always be downloaded to a temporary directory for idempotency checks, otherwise the file will only be downloaded if the package has not been installed based on the product_id checks."

But win_package always downloads/copies the file to a temporary location even if product_id is set and the package is installed

The productId is not being correctly checked in win_package.ps1 this commit fixes that. fixes #479 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_package

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by jborean93** [comment]
Thanks for the PR, unfortunately with the changes here the code will skip downloading the msi into a temp path and when the package is not installed it will fail as it tries to run it from the URI directly instead of the temp file. The code will have to be updated to ensures this scenario continues working.

**Comment by AzadShM** [comment]
That is not correct. The code will check the installation status and use the id for that [win_package.ps1#L1453](../blob/main/plugins/modules/win_package.ps1#L1453). When Get-InstalledStatus does not find the ID and the code is  not in CheckMode the package/msi will be downloaded to a temp path  [win_package.ps1#L1461](../blob/main/plugins/modules/win_package.ps1#L1461) and later installed.

**Comment by AzadShM** [comment]
I now see the problem you are mentioning and it is not because the file is not being downloaded and the URI is being used directly. The problem is that the wrong provider is being used to install the package if the package is not installed and provider is set to auto.
I will check it out and send another commit to fix that.

**Comment by AzadShM** [comment]
The code now runs Get-InstalledStatus twice if state is present, the package is a remote file, productid is set and the package was found not to be installed. The first run is used to avoid downloading/copying the file to a temp folder if it is already installed and the second run is used to determine the correct provider to use for the installation.

Caveats:
* If productid is set to a wrong value the package is always downloaded/copied to a temp path.
* If path is set to a network target, productid is set and state is absent the package is always downloaded/copied to a temp path.
* The product_id parameter documentation says
"[...] This value is ignored if path is set to a local accesible file path and the package is not an exe. [...]"
The product_id is being ignored in most of the cases and not only in the mentioned one.

These caveats are not related to these commits, existed before and are out of scope for this bugfix.

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
