### PR TITLE
Check/Error for using a DSC composite resource

### PR DESCRIPTION
**Pull request by MKletz**
##### SUMMARY
Added a more descriptive error message for unsupported DSC resource types

relevant to #15 but does not fix

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_dsc

##### ADDITIONAL INFORMATION
per the discussion on #15 referencing these types of DSC resources causes the "Failed to serialize properties into CimInstance." which does not clearly explain the issue. I will be working on a PR to add support for these resources but this was a quick easy improvement to add in the mean time.

### CODE REVIEW

**Comment by jborean93** [comment]
I'm not sure if we can easily solve the configuration issue with pslint sanity. We could technically install the OMI components that allow pwsh to parse the file into a MOF but that might be a bit too much bloat to add for a file used just for tests. My recommendation is to just skip this file explicitly in the sanity tests to enable CI to pass.

Basically you want to add the following to https://github.com/ansible-collections/ansible.windows/blob/main/tests/sanity/ignore-2.13.txt (we keep it in alphabetical order)

```
tests/integration/targets/win_dsc/files/xTestCompositeDsc/1.0.0/DSCResources/xTestComposite/xTestComposite.schema.psm1 pslint!skip # Pwsh cannot parse DSC to MOF on Linux
```

This will skip the PSScriptAnalyzer from running against this file entirely which means pwsh will no attempt to read it and convert it to a MOF file.

**Comment by MKletz** [comment]
@jborean93 I believe it's having issues parsing the composite resource not a MOF. There is not a MOF being generated here to my knowledge.

**Comment by jborean93** [comment]
> @jborean93 I believe it's having issues parsing the composite resource not a MOF

What I believe is happening is that when PowerShell parses the file mentioned it generates the MOF as part of that process. On Windows this is fine as the tools are builtin but on Linux/macOS it requires OMI to be present and we don't have that on our images. In the end skipping the `pslint` sanity test is fine for this file as it's just used for testing.

**Comment by MKletz** [comment]
Gotcha, thanks for the help on the ignore. I agree it's not a huge deal.

Merge as you see fit, let me know if there's anything else that needs to be done.

**Review by jborean93 — COMMENTED** [review]
Only thing missing is a changelog fragment. In this case I would say this is mostly a bugfix to produce a better error message so adding a file under https://github.com/ansible-collections/ansible.windows/tree/main/changelogs/fragments with something like should help

```yaml
bugfixes:
- win_dsc - Provide better error message when trying to invoke a composite DSC resource
```

Feel free to adjust the wording as you see fit.
```

**Review by jborean93 — APPROVED** [review]

**Comment by MKletz** [comment]
done, will make sure the changelog fragment is done for future PRs.

**Pull request merged**
